name: parsonskellogg
favicon: null
layout_spectrum: 0.17171523277647793
typography_spectrum: 0.7260767915286124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6020756179932505
  lightness: 0.7551966276951134
  saturation: 0.717985981842503
  rhythmicContrast: 0.7093022768385708
purpose: []
