name: parsonskellogg
favicon: null
layout_spectrum: 0.17171523277647793
typography_spectrum: 0.39761
title: ParsonsKellogg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f5364'
    - '#72a94e'
    - '#a2abb3'
    - '#6f7e8a'
  brandStrength: 0.625
  lightness: 0.7551966276951134
  saturation: 0.717985981842503
  rhythmicContrast: 0.7093022768385708
purpose: []
